FROM ubuntu:oracular

RUN apt-get update \
    && apt-get install -y \
    python3 \
    python3-venv \
    curl \
    && apt-get install -y --no-install-recommends \
    git \
    openssh-client \
    wget \
    gpg \
    && rm -rf /var/lib/apt/lists/*

# Use venv to install Playwright dependencies
WORKDIR /playwright

RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip install playwright \
    && playwright install-deps chromium \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /playwright

# Run application in development mode
RUN USER_NAME=$(getent passwd 1000 | cut -d: -f1); \
    if [ -n "$USER_NAME" ]; then \
        userdel "$USER_NAME"; \
    fi

RUN GROUP_NAME=$(getent group 1000 | cut -d: -f1); \
    if [ -n "$GROUP_NAME" ]; then \
        groupdel "$GROUP_NAME"; \
    fi

# Create and change to non-root user
RUN groupadd --gid 1000 devrunner \
    && useradd --uid 1000 --gid 1000 -m devrunner

# Change to non-root user and enter home directory
USER devrunner

# Create and enter src folder
RUN mkdir /home/devrunner/src
WORKDIR /home/devrunner/src

# Install dependencies
RUN python3 -m venv venv \
    && . venv/bin/activate \
    && pip install playwright \
    pandas \
    xlrd \
    openpyxl \
    && playwright install chromium

# Move temporally venv folder
RUN mv venv ../

# Create runtime dir
ENV XDG_RUNTIME_DIR=/tmp/runtime-dir
RUN mkdir $XDG_RUNTIME_DIR \
    && chmod 0700 $XDG_RUNTIME_DIR

# Create data folders
RUN mkdir /home/devrunner/data

COPY --chown=devrunner:devrunner ./scripts/docker-run-dev.sh /home/devrunner/
ENTRYPOINT ["/home/devrunner/docker-run-dev.sh"]

