services:
  jr-insc:
    image: elbromasmc/jr-insc
    network_mode: "pasta"
    volumes:
      - jr-insc-data:/home/runner/data
    restart: no
    environment:
      - DATA_DIR=/home/runner/data
      - ENV=prod
      - SEACE_USER=${SEACE_USER}
      - SEACE_PASS=${SEACE_PASS}

volumes:
  jr-insc-data:

